version: '3'

services:
  hr-server:
    environment:
      NODE_ENV: production
      PORT: 80
      POSTGRES_HOST: hr-db
      POSTGRES_PORT: 5432
    env_file:
      - docker.env
    depends_on:
      - hr-db
    build:
      context: ./
      dockerfile: ./Dockerfile
<<<<<<< HEAD
    image: 'hrsystem:latest'
=======
    image: 'hr-system:latest'
>>>>>>> 7801b11e2576f8cf931e6898567392512888a1d4
    ports:
      - '3000:3000'
  hr-db:
    image: 'postgres:13'
    environment:
      POSTGRES_PORT: 5432
    env_file:
      - docker.env
    ports:
      - '25432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
